src/ContosoWeb/Controllers/CheckoutController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Contoso.Models;
using ContosoWeb.Utils;

namespace ContosoWeb.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        private readonly IContosoWebContext db;

        public CheckoutController(IContosoWebContext context)
        {
            db = context;
        }

        const string PromoCode = "FREE";

        //
        // GET: /Checkout/

        public async Task<ActionResult> AddressAndPayment()
        {
            var id = User.Identity.GetUserId();
            var user = await db.Users.FirstOrDefaultAsync(o => o.Id == id);

            var order = new Order
            {
                Name = user.Name,
                Email = user.Email,
                Username = user.UserName
            };

            return View(order);
        }

        //
        // POST: /Checkout/AddressAndPayment

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddressAndPayment(Order order)
        {
            var formCollection = Request.Form;

            try
            {
                if (string.Equals(formCollection.GetValues("PromoCode").FirstOrDefault(), PromoCode,
                    StringComparison.OrdinalIgnoreCase) == false)
                {
                    return View(order);
                }
                else
                {
                    order.Username = User.Identity.GetUserName();
                    order.OrderDate = DateTime.Now;

                    //Add the Order
                    db.Orders.Add(order);

                    //Process the order
                    var cart = ShoppingCart.GetCart(db,CartId.GetCartId( HttpContext));
                    cart.CreateOrder(order);

                    // Save all changes
                    await db.SaveChangesAsync(CancellationToken.None);

                    return RedirectToAction("Complete", new { id = order.OrderId });
                }
            }
            catch
            {
                //Invalid - redisplay with errors
                return View(order);
            }
        }

        //
        // GET: /Checkout/Complete

        public ActionResult Complete(int id)
        {
            // Validate customer owns this order
            var username = User.Identity.GetUserName();

            Order order = db.Orders.First(
                o => o.OrderId == id &&
                o.Username == username);

            if (order != null)
            {
                return View(order);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

src/ContosoWeb/Controllers/OrdersController.cs
using ContosoWeb.Utils;
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Contoso.Models;
using ContosoWeb.ViewModels;

namespace ContosoWeb.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrdersQuery _ordersQuery;
        private readonly ITelemetryProvider _telemetry;

        public OrdersController(IOrdersQuery ordersQuery, ITelemetryProvider telemetryProvider)
        {
            _ordersQuery = ordersQuery;
            _telemetry = telemetryProvider;
        }

        public async Task<ActionResult> Index(DateTime? start, DateTime? end, string invalidOrderSearch)
        {
            var username = User.Identity.GetUserName();

            return View(await _ordersQuery.IndexHelperAsync(username, start, end, invalidOrderSearch, false));
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                _telemetry.TrackTrace("Order/Server/NullId");
                return RedirectToAction("Index", new { invalidOrderSearch = Request.QueryString["id"] });
            }

            var order = await _ordersQuery.FindOrderAsync(id.Value);
            var username = User.Identity.GetUserName();

            // If the username isn't the same as the logged in user, return as if the order does not exist
            if (order == null || !String.Equals(order.Username, username, StringComparison.Ordinal))
            {
                _telemetry.TrackTrace("Order/Server/UsernameMismatch");
                return RedirectToAction("Index", new { invalidOrderSearch = id.ToString() });
            }

            // Capture order review event for analysis
            var eventProperties = new Dictionary<string, string>()
                {
                    {"Id", id.ToString() },
                    {"Username", username }
                };
            if (order.OrderDetails == null)
            {
                _telemetry.TrackEvent("Order/Server/NullDetails", eventProperties, null);
            }
            else
            {
                var eventMeasurements = new Dictionary<string, double>()
                {
                    {"LineItemCount", order.OrderDetails.Count }
                };
                _telemetry.TrackEvent("Order/Server/Details", eventProperties, eventMeasurements);
            }

            var itemsCount = order.OrderDetails.Sum(x => x.Quantity);
            var subTotal = order.OrderDetails.Sum(x => x.Quantity * x.Product.Price);
            var shipping = itemsCount * (decimal)5.00;
            var tax = (subTotal + shipping) * (decimal)0.05;
            var total = subTotal + shipping + tax;

            var costSummary = new OrderCostSummary
            {
                CartSubTotal = subTotal.ToString("C"),
                CartShipping = shipping.ToString("C"),
                CartTax = tax.ToString("C"),
                CartTotal = total.ToString("C")
            };

            var viewModel = new OrderDetailsViewModel
            {
                OrderCostSummary = costSummary,
                Order = order
            };

            return View(viewModel);
        }
    }
}

src/ContosoWeb/Views/Checkout/AddressAndPayment.cshtml
@model Contoso.Models.Order

@{
    ViewBag.Title = "Address And Payment";
}

@section Scripts {
    @Scripts.Render("~/bundles/jquery.validate")
}

<section>
    <h2>Address And Payment</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
<div class="row">
            <div class="col-sm-12 col-md-6 col-border-md-right no-gutter-xs">
                <div class="col-xs-12 no-gutter-sm">
                    <h4>Shipping Information</h4>
                </div>
                <div class="form-group col-sm-8 col-md-10 no-gutter-sm">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                    @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-8 col-md-10 no-gutter-sm">
                    @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", placeholder = "Phone" })
                    @Html.ValidationMessageFor(m => m.Phone, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-8 col-md-10 no-gutter-sm">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email Address" })
                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-8 col-md-10 no-gutter-sm">
                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control", placeholder = "Address" })
                    @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-8 col-md-10 no-gutter-sm">
                    @Html.TextBoxFor(m => m.City, new { @class = "form-control", placeholder = "City" })
                    @Html.ValidationMessageFor(m => m.City, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-8 col-md-10 no-gutter-sm">
                    @Html.TextBoxFor(m => m.State, new { @class = "form-control", placeholder = "State" })
                    @Html.ValidationMessageFor(m => m.State, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-8 col-md-10 no-gutter-sm">
                    @Html.TextBoxFor(m => m.PostalCode, new { @class = "form-control", placeholder = "Postal Code" })
                    @Html.ValidationMessageFor(m => m.PostalCode, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-8 col-md-10 no-gutter-sm">
                    @Html.TextBoxFor(m => m.Country, new { @class = "form-control", placeholder = "Country" })
                    @Html.ValidationMessageFor(m => m.Country, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-sm-12 col-md-6 wide-col-padding no-gutter-xs">
                <div class="col-xs-12  no-gutter-sm">
                    <h4>Payment</h4>
                </div>
                <div class="col-md-12 no-gutter-sm" >
                    <p>We're running a promotion.</p>
                    <p>All parts are free with the promo code: "FREE"</p>
                </div>
                <div class="form-group col-sm-8 col-md-10 no-gutter-sm">
                    @Html.TextBox("PromoCode", null, new { @class = "form-control", placeholder = "Promo Code" })
                </div>
                <div class="col-md-12 no-gutter-sm">
                    <input type="submit" value="Submit Order" />
                </div>

            </div>
            </div>
    }
</section>

src/ContosoWeb/Views/Checkout/Complete.cshtml
@model Contoso.Models.Order

@{
    ViewBag.Title = "Checkout Complete";
}
<section id="complete-page">
<h2>Checkout Complete</h2>

<div class="row">
<div class="col-sm-12">
<p>Thanks for your order!</p>
<p>Your order number is: @Model.OrderId</p>
<p>Order Date: @Model.OrderDate.ToShortDateString()</p>
<p>
    You can @Html.ActionLink("view your order", "Details", "Orders", new{ id = @Model.OrderId}, new{ @class="action-link"}) from your account page.
</p>
<br/>
<p>
	@Html.ActionLink("Keep Shopping", "Index", "Home", null, new{ @class="btn"})
</p>

</div>
</div>
</section>