src/ContosoWeb/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Mvc;
using Contoso.Models;
using ContosoWeb.Utils;
using ContosoWeb.ViewModels;


namespace ContosoWeb.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IContosoWebContext db;
        private readonly ITelemetryProvider telemetry;

        public ShoppingCartController(IContosoWebContext context, ITelemetryProvider telemetryProvider)
        {
            db = context;
            telemetry = telemetryProvider;
        }

        //
        // GET: /ShoppingCart/

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(db, CartId.GetCartId(HttpContext));
            var items = cart.GetCartItems();
            var itemsCount = items.Sum(x => x.Count);
            var subTotal = items.Sum(x => x.Count * x.Product.Price);
            var shipping = itemsCount * (decimal)5.00;
            var tax = (subTotal + shipping) * (decimal)0.05;
            var total = subTotal + shipping + tax;

            var costSummary = new OrderCostSummary
            {
                CartSubTotal = subTotal.ToString("C"),
                CartShipping = shipping.ToString("C"),
                CartTax = tax.ToString("C"),
                CartTotal = total.ToString("C")
            };


            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = items,
                CartCount = itemsCount,
                OrderCostSummary = costSummary
            };


            // Track cart review event with measurements
            telemetry.TrackTrace("Cart/Server/Index");

            // Return the view
            return View(viewModel);
        }

        //
        // GET: /ShoppingCart/AddToCart/5

        public async Task<ActionResult> AddToCart(int id)
        {
            // Retrieve the product from the database
            var addedProduct = db.Products
                .Single(product => product.ProductId == id);

            // Start timer for save process telemetry
            var startTime = DateTime.Now;

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(db, CartId.GetCartId(HttpContext));

            cart.AddToCart(addedProduct);

            await db.SaveChangesAsync(CancellationToken.None);

            // Trace add process
            var measurements = new Dictionary<string, double>()
            {
                {"ElapsedMilliseconds", DateTime.Now.Subtract(startTime).TotalMilliseconds }
            };
            telemetry.TrackEvent("Cart/Server/Add", null, measurements);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveFromCart([FromUri] int id)
        {

            // Start timer for save process telemetry
            var startTime = DateTime.Now;

            // Retrieve the current user's shopping cart
            var cart = ShoppingCart.GetCart(db, CartId.GetCartId(HttpContext));

            // Get the name of the product to display confirmation
            var cartItem = db.CartItems.Include("Product").Single(item => item.CartItemId == id);
            string productName = cartItem.Product.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            await db.SaveChangesAsync(CancellationToken.None);

            string removed = (itemCount > 0) ? " 1 copy of " : string.Empty;

            // Trace remove process
            var measurements = new Dictionary<string, double>()
            {
                {"ElapsedMilliseconds", DateTime.Now.Subtract(startTime).TotalMilliseconds }
            };
            telemetry.TrackEvent("Cart/Server/Remove", null, measurements);

            // Display the confirmation message
            var items = cart.GetCartItems();
            var itemsCount = items.Sum(x => x.Count);
            var subTotal = items.Sum(x => x.Count * x.Product.Price);
            var shipping = itemsCount * (decimal)5.00;
            var tax = (subTotal + shipping) * (decimal)0.05;
            var total = subTotal + shipping + tax;

            var results = new ShoppingCartRemoveViewModel
            {
                Message = removed + productName +
                    " has been removed from your shopping cart.",
                CartSubTotal = subTotal.ToString("C"),
                CartShipping = shipping.ToString("C"),
                CartTax = tax.ToString("C"),
                CartTotal = total.ToString("C"),
                CartCount = itemsCount,
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

    }
}

src/ContosoWeb/Controllers/StoreController.cs
using Contoso.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Runtime.Caching;
using System.Web.Mvc;
using ContosoWeb.Utils;
using ContosoWeb.ViewModels;

namespace ContosoWeb.Controllers
{
    public class StoreController : Controller
    {
        private readonly IContosoWebContext db;

        public StoreController(IContosoWebContext context)
        {
            db = context;
        }

        //
        // GET: /Store/
        public ActionResult Index()
        {
            var genres = db.Categories.ToList();

            return View(genres);
        }

        //
        // GET: /Store/Browse?genre=Disco
        public ActionResult Browse(int categoryId)
        {
            // Retrieve Category genre and its Associated associated Products products from database
            var genreModel = db.Categories.Include("Products").Single(g => g.CategoryId == categoryId);

            return View(genreModel);
        }

        public ActionResult Details(int id)
        {

            var productCacheKey = string.Format("product_{0}", id);
            var product = MemoryCache.Default[productCacheKey] as Product;
            if (product == null)
            {
                product = db.Products.Single(a => a.ProductId == id);
                //Remove it from cache if not retrieved in last 10 minutes
                MemoryCache.Default.Add(productCacheKey, product, new CacheItemPolicy { SlidingExpiration = TimeSpan.FromMinutes(10) });
            }
            var viewModel = new ProductViewModel
            {
                Product = product,
                ShowRecommendations = ConfigurationHelpers.GetBool("ShowRecommendations")
            };

            return View(viewModel);
        }

    }
}

src/ContosoWeb/Views/Store/Browse.cshtml
@model Contoso.Models.Category
@{
    ViewBag.Title = "Browse Products";
}

<section class="section-alt">
    <h2>@Model.Name</h2>
    @Html.Partial("_ProductList", Model.Products)
</section>

src/ContosoWeb/Views/Store/Details.cshtml
@model ContosoWeb.ViewModels.ProductViewModel

@{
    ViewBag.Title = string.Format("Product - {0}", Model.Product.Title);
}

@section scripts
{
    @Scripts.Render("~/bundles/jquery.zoom")

    <script type="text/javascript">
        $(function () {
            if ($ && $.fn.zoom) {
                $('#product-image').zoom({ magnify: 1.5 });
            }
        });
    </script>
}
<div id="store-details">
    <section>
        <h2>@Model.Product.Title</h2>
        <div class="row">
            <div class="col-md-4">
                <div class="details-panel">

                    <div class="zoom" id="product-image">
                        <img src="/Images/@Model.Product.ProductArtUrl" alt="@Model.Product.Title" />
                    </div>

                </div>
            </div>
            <div class="col-md-8">
                <div>
                    <h5>USD $@Model.Product.Price</h5>
                </div>
                <div>
                    @if (@Model.Product.Inventory > 0)
                            {
                        <text>In Stock (Ships 1-3 days)</text>
                            }
                            else
                            {
                        <text>@string.Format("Out of Stock (Ships {0}-{1} days)", Math.Max(Model.Product.LeadTime, 1), Model.Product.LeadTime + 2)</text>
                            }
                </div>
                <div>
                    <h4>Description</h4>
                    <p class="text-content">@Model.Product.Description</p>
                </div>

                <div class="details-table">
                    <table class="table table-striped">
                        @foreach (var detail in Model.Product.ProductDetailList)
                        {
                            <tr>
                                <td>@detail.Key</td>
                                <td>@detail.Value</td>
                            </tr>
                        }
                    </table>
                </div>

                <a href="@Url.Action("AddToCart", "ShoppingCart", new { id = Model.Product.ProductId })" class="btn">Add to Cart</a>
            </div>


        </div>
    </section>

    <section class="section-alt">
        <div class="row">
            @if (Model.ShowRecommendations)
            {
                <script>
                    $(function () { getRecommendations("@Model.Product.ProductId"); })
                </script>
                <div id="recommendations-panel"></div>
            }
        </div>
    </section>
</div>

src/ContosoWeb/Views/Store/Index.cshtml
@using ContosoWeb.Utils
@model IEnumerable<Contoso.Models.Category>

@{
    ViewBag.Title = "Store";
}
<section class="section-alt product-list">
    <h2>Browse Categories</h2>
    <div class="row">
        @foreach (var category in Model)
        {
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <div class="list-item-part">
                    <a href="@Url.Action("Browse", "Store", new { categoryId = category.CategoryId })" title="@category.Name">
                        <div class="product-image-container hidden-xs">
                            <div class="image">
                                @Html.Image(@category.ImageUrl, @category.Name)
                            </div>
                            <div class="detail">
                                <h5>@category.Name</h5>
                            </div>
                        </div>

                        <div class="row visible-xs">
                            <div class="col-xs-4 col-sm-12 col-md-12 no-gutter-sm no-gutter image">
                                @Html.Image(@category.ImageUrl, @category.Name)
                            </div>
                            <div class="col-xs-8 col-sm-12 col-md-12 detail">
                                <h4>@category.Name</h4>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        }
    </div>
</section>