src/ContosoWeb/ViewModels/HomeViewModel.cs
using System.Collections.Generic;
using Contoso.Models;

namespace ContosoWeb.ViewModels
{
    public class HomeViewModel
    {
        public Match NextMatch { get; set; }
        public Match CurrentMatch { get; set; }
        public List<Match> PreviousMatches { get; set; }

        public List<Product> NewProducts { get; set; }
        public List<Product> TopSellingProducts { get; set; }
    }
}

src/ContosoWeb/Controllers/HomeController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Contoso.Models;
using ContosoWeb.ViewModels;

namespace ContosoWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly IContosoWebContext _db;
        public int roco_count = 1000;

        public HomeController(IContosoWebContext context)
        {
            _db = context;
        }

        public ActionResult Index()
        {
            var viewModel = GetHomeViewModelMatches();

            // Get most popular products
            viewModel.TopSellingProducts = QueryTopSellingProducts().Take(4).ToList();
            viewModel.NewProducts = QueryNewProducts().Take(4).ToList();

            return View(viewModel);
        }

        public ActionResult Xbox()
        {
            var viewModel = GetHomeViewModelMatches();

            return View("Xbox", "_XboxLayout", viewModel);
        }

        private HomeViewModel GetHomeViewModelMatches()
        {
            var query = QueryMatches();

            var nextMatch = query.Where(x => x.Progress == MatchProgress.Pending)
                                 .OrderBy(x => x.MatchDate)
                                 .FirstOrDefault();

            var currentMatch = query.Where(x => x.Progress == MatchProgress.InProgress)
                                    .OrderBy(x => x.MatchDate)
                                    .FirstOrDefault();

            var previousMatches = query.Where(x => x.Progress == MatchProgress.Completed)
                                       .ToList();

            return new HomeViewModel {
                NextMatch = nextMatch,
                CurrentMatch = currentMatch,
                PreviousMatches = previousMatches
            };
        }


        //stubbing in a recomendations action
        public ActionResult Recomendations()
        {
            ViewBag.Message = "Your application description page.";
            //See file /home/Recomendations.cshtml for initial rendering

            // Group the order details by product and return
            // the products the top recomendations for the recomendations page

            int count = 0;
            while (count < roco_count)
            {
                _db.Products
                    .OrderByDescending(a => a.OrderDetails.Count())
                    .Take(count++)
                    .ToList();
            }

            return View();
        }

        private IQueryable<Match> QueryMatches()
        {
            return _db
                .Matches
                .Include(x => x.HomeTeam)
                .Include(x => x.HomeTeam.Players)
                .Include(x => x.HomeTeamStats)
                .Include(x => x.AwayTeam)
                .Include(x => x.AwayTeam.Players)
                .Include(x => x.AwayTeamStats)
                .AsQueryable();
        }

        private IQueryable<Product> QueryTopSellingProducts()
        {
            // Group the order details by product and return
            // the products with the highest count

            // TODO [EF] We don't query related data as yet, so the OrderByDescending isn't doing anything
            return _db.Products
                      .OrderByDescending(a => a.OrderDetails.Count())
                      .AsQueryable();
        }

        private IQueryable<Product> QueryNewProducts()
        {
            return _db.Products
                      .OrderByDescending(a => a.Created)
                      .AsQueryable();
        }
    }
}

src/ContosoWeb/Controllers/StoreController.cs
using Contoso.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Runtime.Caching;
using System.Web.Mvc;
using ContosoWeb.Utils;
using ContosoWeb.ViewModels;

namespace ContosoWeb.Controllers
{
    public class StoreController : Controller
    {
        private readonly IContosoWebContext db;

        public StoreController(IContosoWebContext context)
        {
            db = context;
        }

        //
        // GET: /Store/
        public ActionResult Index()
        {
            var genres = db.Categories.ToList();

            return View(genres);
        }

        //
        // GET: /Store/Browse?genre=Disco
        public ActionResult Browse(int categoryId)
        {
            // Retrieve Category genre and its Associated associated Products products from database
            var genreModel = db.Categories.Include("Products").Single(g => g.CategoryId == categoryId);

            return View(genreModel);
        }

        public ActionResult Details(int id)
        {

            var productCacheKey = string.Format("product_{0}", id);
            var product = MemoryCache.Default[productCacheKey] as Product;
            if (product == null)
            {
                product = db.Products.Single(a => a.ProductId == id);
                //Remove it from cache if not retrieved in last 10 minutes
                MemoryCache.Default.Add(productCacheKey, product, new CacheItemPolicy { SlidingExpiration = TimeSpan.FromMinutes(10) });
            }
            var viewModel = new ProductViewModel
            {
                Product = product,
                ShowRecommendations = ConfigurationHelpers.GetBool("ShowRecommendations")
            };

            return View(viewModel);
        }

    }
}

src/ContosoWeb/Views/Home/Index.cshtml
@model ContosoWeb.ViewModels.HomeViewModel

@{
    ViewBag.Title = "Home Page";
}

@section prebody {
    @Html.Partial("_Carousel", Model)

    <div class="featured-areas">
        <div class="container">
            <section class="section-alt">
                <div class="row">
                    <div class="area-tile col-xs-12 col-sm-4 col-md-4">
                        <table class="twoColumns">
                            <thead>
                                <tr>
                                    <th>Previous Meetings</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var match in Model.PreviousMatches)
                                {
                                    <tr>
                                        <td>@match.MatchDate.ToString("MM/dd")</td>
                                        <td>
                                            <span class="@(match.WinningTeamId != null && match.WinningTeamId == match.HomeTeam.TeamId ? "boldFont" : string.Empty)">@match.HomeTeam.AbbreviatedName</span>
                                            <span>@(string.Format(" {0} - {1} ", match.HomeTeamScore, match.AwayTeamScore))</span>
                                            <span class="@(match.WinningTeamId != null && match.WinningTeamId == match.AwayTeam.TeamId ? "boldFont" : string.Empty)">@match.AwayTeam.AbbreviatedName</span>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="area-tile col-xs-12 col-sm-4 col-md-4">
                        <h3>Season Goal Leaders</h3>
                        @if (Model.CurrentMatch != null)
                        {
                            <ul>
                                <li class="boldFont">@Model.CurrentMatch.HomeTeam.Name</li>
                                @foreach (var player in Model.CurrentMatch.HomeTeam.Players.OrderByDescending(x => x.GoalsScored).Take(2))
                                {
                                    <li>
                                        <span>@player.Name</span>
                                        <span>@player.GoalsScored</span>
                                    </li>
                                }
                            </ul>
                            <ul>
                                <li class="boldFont">@Model.CurrentMatch.AwayTeam.Name</li>
                                @foreach (var player in Model.CurrentMatch.AwayTeam.Players.OrderByDescending(x => x.GoalsScored).Take(2))
                                {
                                    <li>
                                        <span>@player.Name</span>
                                        <span>@player.GoalsScored</span>
                                    </li>
                                }
                            </ul>
                        }
                        else
                        {
                            <ul>
                                <li class="boldFont">@Model.NextMatch.HomeTeam.Name</li>
                                @foreach (var player in Model.NextMatch.HomeTeam.Players.OrderByDescending(x => x.GoalsScored).Take(2))
                                {
                                    <li>
                                        <span>@player.Name</span>
                                        <span>@player.GoalsScored</span>
                                    </li>
                                }
                            </ul>
                            <ul>
                                <li class="boldFont">@Model.NextMatch.AwayTeam.Name</li>
                                @foreach (var player in Model.NextMatch.AwayTeam.Players.OrderByDescending(x => x.GoalsScored).Take(2))
                                {
                                    <li>
                                        <span>@player.Name</span>
                                        <span>@player.GoalsScored</span>
                                    </li>
                                }
                            </ul>
                        }

                    </div>
                    <div class="area-tile col-xs-12 col-sm-4 col-md-4">
                        @if (Model.CurrentMatch != null)
                        {
                            <table id="liveStatsTable" class="threeColumns" style="display: none;">
                                <thead>
                                    <tr>
                                        <th>@Model.CurrentMatch.HomeTeam.ShortName</th>
                                        <th></th>
                                        <th>@Model.CurrentMatch.AwayTeam.ShortName</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                            <script type="text/javascript">
                                startLiveStatsFeed(@Model.CurrentMatch.MatchId);
                            </script>
                        }
                    </div>
                </div>
            </section>
        </div>
    </div>
}

<!--TODO : Update github link -->
<a href="https://github.com/" class="hidden-xs">
    <img style="position: absolute; top: 0; left: 0; border: 0;" src="https://camo.githubusercontent.com/c6625ac1f3ee0a12250227cf83ce904423abf351/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f677261795f3664366436642e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_gray_6d6d6d.png">
</a>
<div id="home-page">
    <section class="section-alt">
        <h2>Arrivals</h2>
        @Html.Partial("_ProductList", Model.NewProducts)
    </section>
    <section class="section-alt">
        <h2>Top Selling</h2>
        @Html.Partial("_ProductList", Model.TopSellingProducts)
    </section>
    <section class="section-alt">
        <div id="linkTiles" class="row">
            <div class="col-xs-12">
                <a href="@Url.Action("Browse", "Store", new { categoryId = 5 })">
                    <img src="~/images/ticket_button.jpg" alt="Purchase Tickets" class="col-xs-6" />
                </a>
                <a href="#">
                    <img src="~/images/app_button.jpg" alt="Download Contoso SLA application" class="col-xs-6" />
                </a>
            </div>
        </div>
    </section>
</div>

src/ContosoWeb/Views/Home/Recomendations.cshtml
@model IEnumerable<Contoso.Models.Product>
@using ContosoWeb.Utils
@{
    ViewBag.Title = "Home Page";
}
<div class="jumbotron">
    <h1>Contoso Sports Online Store Recommendations</h1>
    <title>Your Recommentations</title>
    <h2>Your recomendations are:</h2>
    Semi Final Tickets
    Men's Jerseys
</div>

     

src/ContosoWeb/Views/Home/Xbox.cshtml
@model ContosoWeb.ViewModels.HomeViewModel

@{
    ViewBag.Title = "Xbox Page";
}

@section prebody {
    @Html.Partial("_Carousel", Model)

    <div class="featured-areas">
        <div class="container">
            <section class="section-alt">
                <div class="row">
                    <div class="area-tile col-xs-12 col-sm-4 col-md-4">
                        <table class="twoColumns">
                            <thead>
                                <tr>
                                    <th>Previous Meetings</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var match in Model.PreviousMatches)
                                {
                                    <tr>
                                        <td>@match.MatchDate.ToString("MM/dd")</td>
                                        <td>
                                            <span class="@(match.WinningTeamId != null && match.WinningTeamId == match.HomeTeam.TeamId ? "boldFont" : string.Empty)">@match.HomeTeam.AbbreviatedName</span>
                                            <span>@(string.Format(" {0} - {1} ", match.HomeTeamScore, match.AwayTeamScore))</span>
                                            <span class="@(match.WinningTeamId != null && match.WinningTeamId == match.AwayTeam.TeamId ? "boldFont" : string.Empty)">@match.AwayTeam.AbbreviatedName</span>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="area-tile col-xs-12 col-sm-4 col-md-4">
                        <h3>Season Goal Leaders</h3>
                        @if (Model.CurrentMatch != null)
                        {
                            <ul>
                                <li class="boldFont">@Model.CurrentMatch.HomeTeam.Name</li>
                                @foreach (var player in Model.CurrentMatch.HomeTeam.Players.OrderByDescending(x => x.GoalsScored).Take(2))
                                {
                                    <li>
                                        <span>@player.Name</span>
                                        <span>@player.GoalsScored</span>
                                    </li>
                                }
                            </ul>
                            <ul>
                                <li class="boldFont">@Model.CurrentMatch.AwayTeam.Name</li>
                                @foreach (var player in Model.CurrentMatch.AwayTeam.Players.OrderByDescending(x => x.GoalsScored).Take(2))
                                {
                                    <li>
                                        <span>@player.Name</span>
                                        <span>@player.GoalsScored</span>
                                    </li>
                                }
                            </ul>
                        }
                        else
                        {
                            <ul>
                                <li class="boldFont">@Model.NextMatch.HomeTeam.Name</li>
                                @foreach (var player in Model.NextMatch.HomeTeam.Players.OrderByDescending(x => x.GoalsScored).Take(2))
                                {
                                    <li>
                                        <span>@player.Name</span>
                                        <span>@player.GoalsScored</span>
                                    </li>
                                }
                            </ul>
                            <ul>
                                <li class="boldFont">@Model.NextMatch.AwayTeam.Name</li>
                                @foreach (var player in Model.NextMatch.AwayTeam.Players.OrderByDescending(x => x.GoalsScored).Take(2))
                                {
                                    <li>
                                        <span>@player.Name</span>
                                        <span>@player.GoalsScored</span>
                                    </li>
                                }
                            </ul>
                        }

                    </div>
                    <div class="area-tile col-xs-12 col-sm-4 col-md-4">
                        @if (Model.CurrentMatch != null)
                        {
                            <table id="liveStatsTable" class="threeColumns" style="display: none;">
                                <thead>
                                    <tr>
                                        <th>@Model.CurrentMatch.HomeTeam.ShortName</th>
                                        <th></th>
                                        <th>@Model.CurrentMatch.AwayTeam.ShortName</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                            <script type="text/javascript">
                                startLiveStatsFeed(@Model.CurrentMatch.MatchId);
                            </script>
                        }
                    </div>
                </div>
            </section>
        </div>
    </div>
}

<!--TODO : Update github link -->
<a href="https://github.com/" class="hidden-xs">
    <img style="position: absolute; top: 0; left: 0; border: 0;" src="https://camo.githubusercontent.com/c6625ac1f3ee0a12250227cf83ce904423abf351/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f677261795f3664366436642e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_gray_6d6d6d.png">
</a>