src/ContosoWeb/Areas/Admin/Controllers/CustomerController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Contoso.Models;

namespace ContosoWeb.Areas.Admin.Controllers
{
    public class CustomerController : AdminController
    {
        private readonly IContosoWebContext _context;

        public CustomerController(IContosoWebContext context)
        {
            _context = context;
        }

        public async Task<ActionResult> Index(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return Redirect("Find");
            }

            var user = await _context.Users.SingleOrDefaultAsync(u => u.Id == id);

            if (user == null)
            {
                return Redirect("Find");
            }

            return View(user);
        }

        public async Task<ActionResult> Find(string username, string email, string phoneNumber)
        {
            IQueryable<ApplicationUser> query = _context.Users;

            if (!string.IsNullOrWhiteSpace(username))
            {
                query = query.Where(u => u.UserName == username);
            }

            if (!string.IsNullOrWhiteSpace(email))
            {
                query = query.Where(u => u.Email == email);
            }

            if (!string.IsNullOrWhiteSpace(phoneNumber))
            {
                query = query.Where(u => u.PhoneNumber == phoneNumber);
            }

            // We only want cases where there is one instance.  SingleOrDefault will throw an exception
            // when there is more than one, so we take two and only use the result if it was the only one
            var result = await query.Take(2).ToListAsync();

            if (result.Count == 1)
            {
                return RedirectToAction("Index", new { id = result[0].Id });
            }

            return View();
        }
    }
}

src/ContosoWeb/Areas/Admin/Views/Customer/Find.cshtml
@{
    ViewBag.Title = "Find Customers";
}

<h2>Search for customers:</h2>

<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            @using (Html.BeginForm("Find", "Customer", FormMethod.Get))
            {
                <div class="form-group">
                    <label for="username">Username</label>
                    <input class="form-control" id="username" name="username" type="text" />
                </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input class="form-control" id="email" name="email" type="email" />
                    </div>
                    <div class="form-group">
                        <label for="phoneNumber">Phone Number:</label>
                        <input class="form-control" id="phoneNumber" name="phoneNumber" type="number" />
                    </div>
                    <button class="btn btn-default" type="submit">Search</button>
            }
        </div>
    </div>
</div>

src/ContosoWeb/Areas/Admin/Views/Customer/Index.cshtml
@model Contoso.Models.ApplicationUser

@{
    ViewBag.Title = string.Format("Customer - {0}", Model.UserName);
}

<br />

<div class="panel panel-default">
    <div class="panel-heading">
        Customer Information
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">
                <dl>
                    <dt>Username</dt>
                    <dd>@Model.UserName</dd>
                </dl>
            </div>
            <div class="col-md-4">
                <dl>
                    <dt>Phone Number</dt>
                    <dd>@Model.PhoneNumber</dd>
                </dl>
            </div>
            <div class="col-md-4">
                <dl>
                    <dt>Email</dt>
                    <dd>@Model.Email</dd>
                </dl>
            </div>
        </div>
    </div>
</div>